---
title: "Jak korzystac z webserwisow"
author: "Przemyslaw Biecek"
date: "6 May 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

```{r}
library(httr)
set_config( config( ssl_verifypeer = 0L ) )
```

## Korekta

Końcówka `spell/single` robi korektę języka.

```{r korekta}

korekta <- POST("https://ec2-54-194-28-130.eu-west-1.compute.amazonaws.com/ams-ws-nlp/rest/spell/single",
     body = list(message=list(body="gotofy do prob?"), token="2$zgITnb02!lV"),
     add_headers("Content-Type" = "application/json"), encode = "json")

content(korekta, "parsed")
```

## Rozkład

Końcówka `nlp/single` robi analizę morfologiczną zadania.

```{r rozklad}
nlp <- POST("https://ec2-54-194-28-130.eu-west-1.compute.amazonaws.com/ams-ws-nlp/rest/nlp/single",
     body = list(message=list(body="Czy jesteś gotowy do pracy?"), token="2$zgITnb02!lV"),
     add_headers("Content-Type" = "application/json"), encode = "json")

content(nlp, "parsed")
```

https://github.com/morfologik/

Kategorie gramatyczne dla mds

http://nlp.ipipan.waw.pl/CORPUS/znakowanie.pdf

## Alternatywa

Jeżeli nie uda wię wyłączyć weryfikacji SSL, pozostaje korzystanie bezpośrednio z zewnętrznego programu curl.

```{r rozpacz}

output <- system('curl -H "Content-Type: application/json" -k -X POST -d \'{"message":{"body":"gotofy do prob?"},"token":"2$zgITnb02!lV"}\' https://ec2-54-194-28-130.eu-west-1.compute.amazonaws.com/ams-ws-nlp/rest/spell/single', intern=TRUE)

jsonlite::fromJSON(output)

```
